// <auto-generated />
namespace WebsiteFPT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class up_guest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up_guest));
        
        string IMigrationMetadata.Id
        {
            get { return "202105271355078_up_guest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
