// <auto-generated />
namespace WebsiteFPT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_variant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_variant));
        
        string IMigrationMetadata.Id
        {
            get { return "202105141643577_update_variant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
